#                    Tensors

## 0-D TENSORS/SCALER

In [28]:
import numpy as np

In [29]:
a=np.array(2) #initialize of --> a

In [30]:
a #print a

array(2)

In [31]:
print("No Of Dimension :",a.ndim)

No Of Dimension : 0


## 1-D TENSORS/VECTOR

In [38]:
b = np.array([1,5,6,9,8,2,4]) #initialize of --> b

In [33]:
b #print b

array([1, 5, 6, 9, 8, 2, 4])

In [34]:
print("No Of Dimension :",b.ndim)

No Of Dimension : 1


## 2-D TENSORS/MATRICES

In [35]:
c = np.array([ [1,2,3,9,5] , [1,8,5,4,7] , [2,3,6,5,4] , [7,8,2,2,3] ]) #initialize of --> c

In [36]:
c #print c

array([[1, 2, 3, 9, 5],
       [1, 8, 5, 4, 7],
       [2, 3, 6, 5, 4],
       [7, 8, 2, 2, 3]])

In [37]:
print("No Of Dimension :",c.ndim)

No Of Dimension : 2


## 3-D TENSORS

In [40]:
d = np.array([ [[1,2,3],[7,8,6]] , [[4,6,9],[4,5,2]] , [[4,7,8],[2,3,9]] ]) #initialize of --> d

In [41]:
d #print d

array([[[1, 2, 3],
        [7, 8, 6]],

       [[4, 6, 9],
        [4, 5, 2]],

       [[4, 7, 8],
        [2, 3, 9]]])

In [42]:
print("No Of Dimension :",d.ndim)

No Of Dimension : 3


## 4-D TENSORS

In [58]:
e = np.array([ [[[1,2,5],[4,5,8],[7,5,2]]] , [[[1,8,6],[8,5,2],[7,5,2]]]  , [[[5,7,58],[25,25,41],[73,54,12]]] ])

In [59]:
e #print e

array([[[[ 1,  2,  5],
         [ 4,  5,  8],
         [ 7,  5,  2]]],


       [[[ 1,  8,  6],
         [ 8,  5,  2],
         [ 7,  5,  2]]],


       [[[ 5,  7, 58],
         [25, 25, 41],
         [73, 54, 12]]]])

In [60]:
print("No Of Dimension :",e.ndim)

No Of Dimension : 4


## 5-D TENSORS

In [61]:
f = np.array([ [[[[8,5,12],[5,3,7],[2,2,0]]]] , [[[[1,9,7],[1,4,2],[4,6,9]]]]  , [[[[54,7,8],[2,50,12],[30,47,78]]]] ])

In [62]:
f #print f

array([[[[[ 8,  5, 12],
          [ 5,  3,  7],
          [ 2,  2,  0]]]],



       [[[[ 1,  9,  7],
          [ 1,  4,  2],
          [ 4,  6,  9]]]],



       [[[[54,  7,  8],
          [ 2, 50, 12],
          [30, 47, 78]]]]])

In [57]:
print("No Of Dimension :",f.ndim)

No Of Dimension : 5
